apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  hostPath: 
  path: "/postgres/data"
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    request:
      storage: 1Gi
