apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage-class
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  storageClassName: db-storage-class
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteOnce

