apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/postgres/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteOnce

